title: Aj Jones
logo: /assets/img/profile.png
description:
  Software Engineer | Game Dev | Dad <br> 
  B.S. Computer Science <br> 
  Cal State San Marcos.  <br>
  Check out <a href="https://www.welltold.games/the-foglands">The Foglands!</a>

github:
  is_project_page: false
  is_user_page: false



# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


exclude: 
 - _posts/templates/
